#define ERROR_INVALID_PARAMS 1
#define ERROR_MALFORMED_DIMENSION_PARAM 2
#define ERROR_UNSUPPORTED_TYPE 3
#define ERROR_UNSUPPORTED_WAV 4
#define ERROR_INVALID_IMAGE_DIMENSIONS 5
#define ERROR_LOAD_MEDIA_FAIL 6
#define ERROR_WRITE_MEDIA_FAIL 7